<a href="https://colab.research.google.com/github/ruman23/ML-Data-Preprocessing/blob/main/ML_data_preprocessing_tools.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing Tools

## Importing the libraries

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [4]:
df = pd.read_csv('Data.csv') 
x = df.iloc[:, :3].values
y = df.iloc[:, -1].values
print(x)
print('------------------------------')
print(y)


[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
------------------------------
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data

In [5]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


# *Encoindg the independent variable* 

In [6]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder 
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

print(x)


[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


# Encoding the dependent variable 

In [12]:
from sklearn.preprocessing import LabelEncoder 
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [13]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.3, random_state = 1)
print(x_train)
print('------------------------------')
print(x_test)
print('------------------------------')
print(y_train)
print('------------------------------')
print(y_test)


[[0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]
------------------------------
[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]]
------------------------------
[1 0 0 1 1 0 1]
------------------------------
[0 1 0]


## Feature Scaling

In [39]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler() 
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.fit_transform(x_test[:, 3:])
print(x_train)
print('------------------------------')
print(x_test)

[[-0.8660254037844387 1.5811388300841895 -0.6324555320336759
  -0.03891021128204816 -0.22960023388015172]
 [1.1547005383792517 -0.6324555320336759 -0.6324555320336759
  0.5058327466666259 0.491205348846628]
 [-0.8660254037844387 -0.6324555320336759 1.5811388300841895
  -0.31128169025638514 -0.4731156334500102]
 [-0.8660254037844387 -0.6324555320336759 1.5811388300841895
  -1.8093248246152385 -1.612767703436946]
 [1.1547005383792517 -0.6324555320336759 -0.6324555320336759
  1.0505757046152997 1.1048641557626706]
 [-0.8660254037844387 1.5811388300841895 -0.6324555320336759
  1.3229471835896367 1.4555263311432662]
 [1.1547005383792517 -0.6324555320336759 -0.6324555320336759
  -0.7198389087178906 -0.7361122649854568]]
------------------------------
[[0.0 1.4142135623730951 -0.7071067811865476 -1.3880272079128577
  -0.5513801778287941]
 [1.0 -0.7071067811865476 -0.7071067811865476 0.4594174561401711
  1.4035131799278395]
 [0.0 -0.7071067811865476 1.4142135623730951 0.9286097517726866
  -0.8